# Generated by Django 6.0.4 on 2026-04-14 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('overall_rating', models.IntegerField()),
                ('potential', models.IntegerField()),
                ('pace', models.IntegerField(blank=True, null=True)),
                ('shooting', models.IntegerField(blank=True, null=True)),
                ('passing', models.IntegerField(blank=True, null=True)),
                ('dribbling', models.IntegerField(blank=True, null=True)),
                ('defending', models.IntegerField(blank=True, null=True)),
                ('physical', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FWD', 'Forward')], max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
            ],
        ),
    ]
