# Generated by Django 6.0.4 on 2026-04-14 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('national_position', models.CharField(blank=True, max_length=20)),
                ('club_position', models.CharField(blank=True, max_length=20)),
                ('rating', models.IntegerField()),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('skill_moves', models.IntegerField(blank=True, null=True)),
                ('ball_control', models.IntegerField(blank=True, null=True)),
                ('dribbling', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('strength', models.IntegerField(blank=True, null=True)),
                ('player_level', models.CharField(blank=True, choices=[('Elite', 'Elite'), ('Top', 'Top'), ('Mid', 'Mid'), ('Low', 'Low')], max_length=20)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
            ],
        ),
    ]
